[package]
name = "rlox"
version = "0.1.0"
authors = ["Adam Biltcliffe <adam.biltcliffe@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_enum = "0.5.1"
